name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Set up JDK
        uses: actions/setup-java@4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@4
        with:
          name: MiddleClicker-APK
          path: app/build/outputs/apk/debug/app-debug.apk
